import re
from playwright.sync_api import Playwright, sync_playwright, expect
import pytest

@pytest.mark.skip(reason="Тест временно запускать не надо, т.к. сервер подвисает")
def test_fill_form2(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://demoqa.com/automation-practice-form")
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").fill("Tatiana")
    page.get_by_role("textbox", name="First Name").press("Tab")
    page.get_by_role("textbox", name="Last Name").fill("Y")
    page.get_by_role("textbox", name="Last Name").press("Tab")
    page.get_by_role("textbox", name="name@example.com").fill("mail@mail.ru")
    page.get_by_role("textbox", name="name@example.com").press("Tab")
    page.get_by_role("radio", name="Male", exact=True).press("Tab")
    page.get_by_text("Female").click()
    page.get_by_role("textbox", name="Mobile Number").click()
    page.get_by_role("textbox", name="Mobile Number").fill("555555")
    page.locator("#dateOfBirthInput").click()
    page.get_by_role("combobox").nth(1).select_option("2010")
    page.get_by_role("option", name="Choose Friday, January 1st,").click()
    page.locator(".subjects-auto-complete__value-container").click()
    page.locator("div").filter(has_text=re.compile(r"^Sports$")).click()
    page.get_by_text("Sports").click()
    page.locator("div").filter(has_text=re.compile(r"^Sports$")).click()
    page.get_by_text("Reading").click()
    page.locator(".subjects-auto-complete__value-container").click()
    page.locator("#subjectsInput").fill("?")
    page.get_by_role("button", name="Select picture").click()
    page.get_by_role("button", name="Select picture").set_input_files("test.txt")
    page.get_by_role("textbox", name="Current Address").click()
    page.get_by_role("textbox", name="Current Address").fill("sdfks;jdglk;sdjg")
    page.locator(".css-19bqh2r").first.click()
    page.get_by_text("Uttar Pradesh", exact=True).click()
    page.locator(".css-1gtu0rj-indicatorContainer").click()
    page.get_by_text("Rajasthan", exact=True).click()
    page.locator("div").filter(has_text=re.compile(r"^Select City$")).nth(3).click()
    page.get_by_text("Jaipur", exact=True).click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("textbox", name="Mobile Number").click()
    page.get_by_role("textbox", name="Mobile Number").fill("0123456789")
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="Close").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()
